SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER loginTrig
AFTER INSERT
ON INTERN_DETAILS
BEGIN
 DBMS_OUTPUT.PUT_LINE('Application is submitted');
 END;
 /
 
 
 CREATE OR REPLACE TRIGGER deleteTrig
AFTER DELETE
ON INTERN_DETAILS
BEGIN
 DBMS_OUTPUT.PUT_LINE('Your account is deleted');
 END;
 /
 COMMIT;